server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investment_platform?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # This creates tables automatically from your entities
    show-sql: true  # Shows SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com  # Replace with your Gmail
    password: your-app-password     # Replace with your Gmail App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

app:
  frontend-url: http://localhost:3000